* SRFI 113: Sets and bags

** by John Cowan

This repository hosts [[http://srfi.schemers.org/srfi-113/][SRFI 113]]: Sets and bags, a [[http://srfi.schemers.org/][Scheme Request for Implementation]].

This SRFI is in /final/ status.

The full documentation for this SRFI can be found in the [[http://srfi.schemers.org/srfi-113/srfi-113.html][SRFI Document]].

If you'd like to participate in the discussion of this SRFI, or report issues with it, please [[http://srfi.schemers.org/srfi-113/][join the SRFI-113 mailing list]] and send your message there.

Thank you.


[[mailto:srfi-editors@srfi.schemers.org][The SRFI Editors]]

* SRFI 113 - Sets and Bags

This repository hosts a reference implementation of SRFI 113 - Sets
and Bags.  The full documentation for this SRFI can be found on the
[[http://srfi.schemers.org/srfi-113/][SRFI Document Reference]].  The repository hosts a complete
implementation of the SRFI, running on [[http://call-cc.org][CHICKEN]] Scheme.

** File Description

While this repository is primarily to provide a reference
implementation of SRFI 113, it also currently serves as the base
repository to host the library as a CHICKEN extension (egg).  Thus,
there are three files that are independent of the SRFI itself, and are
as follows:

=srfi-113.meta= : This file denotes metadata about the CHICKEN
extension, such as author, license, and dependencies (and dependencies
for tests).

=srfi-113.setup= : This file tells the CHICKEN package manager
(=chicken-install=) how to build the egg.

=srfi-113.release-info= : Describes the URL / different releases of the
CHICKEN extension.

Additionally, the =tests/= directory has been added to accommodate the
CHICKEN package manager (for running tests).  Currently it provides a
default test runner which merely includes the tests found in the
=ilists/= directory.

** License

Provided under a single clause BSD license, Copyright (C) John Cowan
2015.  See LICENSE for full details.
